### ISSUE TITLE
BUG: Recipe like feature does not work

### ISSUE THREAD

**Issue by mehul-m-prajapati** [AlfiyaSiddique/TastyTrails#379]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

Recipe like feature does not work

### Steps to reproduce

Go To Recipe -> Hit like

![Animation5](https://github.com/user-attachments/assets/7e671681-620a-4f82-84c4-b03667f2e29a)

```
CastError: Cast to ObjectId failed for value "undefined" (type string) at path "_id" for model "Recipe"
    at SchemaObjectId.cast (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\schema\objectId.js:250:11)
    at SchemaType.applySetters (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\schemaType.js:1236:12)
    at SchemaType.castForQuery (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\schemaType.js:1653:17)
    at cast (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\cast.js:389:32)
    at Query.cast (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\query.js:4868:12)
    at Query._castConditions (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\query.js:2265:10)
    at model.Query._findOne (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\query.js:2589:8)
    at model.Query.exec (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\query.js:4412:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getComments (file:///D:/Projects/GsSoc/TastyTrails/backend/Controllers/RecipeController.js:407:20) {
  stringValue: '"undefined"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: 'undefined',
  path: '_id',
  reason: BSONError: input must be a 24 character hex string, 12 byte Uint8Array, or an integer
      at new ObjectId (D:\Projects\GsSoc\TastyTrails\backend\node_modules\bson\lib\bson.cjs:2388:23)
      at castObjectId (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at SchemaObjectId.cast (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\schema\objectId.js:248:12)
      at SchemaType.applySetters (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\schemaType.js:1236:12)
      at SchemaType.castForQuery (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\schemaType.js:1653:17)
      at cast (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\cast.js:389:32)
      at Query.cast (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\query.js:4868:12)
      at Query._castConditions (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\query.js:2265:10)
      at model.Query._findOne (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\query.js:2589:8)
      at model.Query.exec (D:\Projects\GsSoc\TastyTrails\backend\node_modules\mongoose\lib\query.js:4412:80),
  valueType: 'string'
}
Fetching comments for recipe: 671efe14457bd66172c0bbc3
```

### What was the expected result?

Recipe like should get increased

### Proposed solution

Fix mongo query

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by mehul-m-prajapati** [comment]
@AlfiyaSiddique: Please assign it to me

**Comment by AlfiyaSiddique** [comment]
@mehul-m-prajapati go ahead.
Also remove the feature for opening the recipe when heart is clicked just increase the number and make it red
